<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application' => '',
    'Are you sure?' => '',
    'Attempt' => '',
    'Attempts' => '',
    'Attempts ({attempts})' => '',
    'Buried' => '',
    'Class' => '',
    'Contains' => '',
    'Context' => '',
    'Data' => '',
    'Delay' => '',
    'Details' => '',
    'Done' => '',
    'Done successfully' => '',
    'Duration' => '',
    'Empty' => '',
    'Environment' => '',
    'Error' => '',
    'Exec' => '',
    'Filtered' => '',
    'Finished' => '',
    'Has failed attempts' => '',
    'Host' => '',
    'ID' => '',
    'In progress' => '',
    'Is retry?' => '',
    'Job' => '',
    'Job UID' => '',
    'Jobs' => '',
    'Last execute time and memory usage.' => '',
    'Mark as stopped.' => '',
    'Memory Usage' => '',
    'Name' => '',
    'No jobs found.' => '',
    'No workers found.' => '',
    'Number of attempts.' => '',
    'PID' => '',
    'Push Again' => '',
    'Push Context' => '',
    'Push TTR' => '',
    'Push Trace' => '',
    'Push again.' => '',
    'Pushed' => '',
    'Queue Monitor' => '',
    'Reset' => '',
    'Scope' => '',
    'Sender' => '',
    'Started' => '',
    'Started At' => '',
    'Status' => '',
    'Stop' => '',
    'Stop the worker.' => '',
    'Stopped' => '',
    'Sub Jobs' => '',
    'TTR' => '',
    'Time to reserve of the job.' => '',
    'Total Done' => '',
    'Total Started' => '',
    'Value' => '',
    'Wait' => '',
    'Wait Time' => '',
    'Waiting' => '',
    'Waiting time from push till first execute.' => '',
    'Workers' => '',
    'empty lead' => '',
    'from' => '',
];
