<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application' => 'Приложение',
    'Are you sure?' => 'Вы уверены?',
    'Attempt' => 'Попытка',
    'Attempts' => 'Попытки',
    'Attempts ({attempts})' => 'Попыток ({attempts})',
    'Buried' => '',
    'Class' => 'Класс',
    'Contains' => 'Содержит',
    'Context' => 'Контекст',
    'Data' => 'Данные',
    'Delay' => 'Задержка',
    'Details' => 'Подробности',
    'Done' => 'Выполнено',
    'Done successfully' => 'Успешно выполнено',
    'Duration' => 'Длительность',
    'Empty' => 'Ничего не найдено',
    'Environment' => 'Окружение',
    'Error' => 'Ошибка',
    'Exec' => 'Выполнение',
    'Filtered' => 'Отфильтровано',
    'Finished' => 'Завершено',
    'Has failed attempts' => 'С неудачными попытками',
    'Host' => 'Хост',
    'ID' => 'ID',
    'In progress' => 'В процессе',
    'Is retry?' => 'Повтор?',
    'Job' => 'Задача',
    'Job UID' => 'ID Задачи',
    'Jobs' => 'Задачи',
    'Last execute time and memory usage.' => 'Время последнего выполнения и использование памяти',
    'Mark as stopped.' => 'Остановить',
    'Memory Usage' => 'Использование памяти',
    'Name' => 'Название',
    'No jobs found.' => 'Задач не найдено.',
    'No workers found.' => 'Исполнителей не найдено.',
    'Number of attempts.' => 'Кол-во попыток',
    'PID' => 'PID',
    'Push Again' => 'Перезапустить',
    'Push Context' => 'Контекст задачи',
    'Push TTR' => 'TTR',
    'Push Trace' => 'Отладочная информация',
    'Push again.' => 'Повторный запуск задачи',
    'Pushed' => 'Запущено',
    'Queue Monitor' => 'Менеджер очередей',
    'Reset' => 'Сброс',
    'Scope' => 'Статус',
    'Sender' => 'Отправитель',
    'Started' => 'Запущено',
    'Started At' => 'Запущено в',
    'Status' => 'Статус',
    'Stop' => 'Остановить',
    'Stop the worker.' => 'Остановить процесс',
    'Stopped' => 'Остановлено',
    'Sub Jobs' => 'Подзадачи',
    'TTR' => 'TTR',
    'Time to reserve of the job.' => 'Время резервирования задачи',
    'Total Done' => 'Всего исполнено',
    'Total Started' => 'Всего запущено',
    'Value' => 'Значение',
    'Wait' => 'Ожидание',
    'Wait Time' => 'Время ожидания',
    'Waiting' => 'В ожидании',
    'Waiting time from push till first execute.' => 'Время ожидания с момента постановки до первого выполнения',
    'Workers' => 'Исполнители',
    'empty lead' => 'ничего не найдено',
    'from' => 'из',
];
