<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Push is forbidden.' => 'Перезапуск задачи запрещен',
    'Record not found.' => 'Запись не найдена',
    'Stop is forbidden.' => 'Прерывание задачи запрещено',
    'The job is already done.' => 'Задача уже выполнена',
    'The job is already stopped.' => 'Задача уже остановлена',
    'The job is pushed again.' => 'Задача отправлена в очередь повторно',
    'The job isn\'t pushed because it must be JobInterface instance.' => 'Задача не может быть добавлена, задача должна реализовывать интерфейс JobInterface ',
    'The job isn\'t pushed because {sender} component isn\'t found.' => 'Задача не может быть добавлена, компонент - отправитель не найден',
    'The job will be stopped.' => 'Задача будет остановлена',
    'The worker will be stopped within {timeout} sec.' => 'Исполнитель будет остановлен в течение {timeout} сек.',
];
